export enum AuthConstants {
  PASSPORT_STRATEGY = "local",
  JWT_SECRET = "DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.",
  JWT_EXPIRESIN = "1d",
}
